### PR TITLE
Fix Dockerfile for multiqc vs new python

### PR DESCRIPTION
**Pull request by marcodelapierre**

### CODE REVIEW

**Review by pditommaso — APPROVED** [review]

**Comment by pditommaso** [comment]
Interesting, wonder if `wave --conda-package multiqc=1.17 ` works of if it's broken as well

**Comment by emi80** [comment]
@pditommaso, indeed `wave --conda-package multiqc=1.17` works as I have been using that version in my tests with Singularity 4

**Comment by marcodelapierre** [comment]
interesting! below is what I needed for it to work:

- python < 3.12
- typing_extensions
- importlib_metadata


```
FROM mambaorg/micromamba
MAINTAINER Paolo Di Tommaso <paolo.ditommaso@gmail.com>

RUN \
   micromamba install -y -n base -c defaults -c bioconda -c conda-forge \
      salmon=1.10.2 \
      fastqc=0.12.1 \
      multiqc=1.17 \
      python=3.11 \
      typing_extensions \
      importlib_metadata \
      procps-ng \
   && micromamba clean -a -y

ENV PATH="$MAMBA_ROOT_PREFIX/bin:$PATH"
USER root
```

**Comment by marcodelapierre** [comment]
CI fails due to current image on quay.io:

In https://github.com/nextflow-io/rnaseq-nf/actions/runs/6770165713/workflow?pr=23:
```
    - name: Tests
        run: |
          curl -fsSL get.nextflow.io | bash
          ./nextflow run . -profile docker
        env:
          NXF_ANSI_LOG: false
```

In `nextflow.config`:
```
  docker {
    process.container = 'quay.io/nextflow/rnaseq-nf:v1.2.1'
    docker.enabled = true
  }
```

**Comment by pditommaso** [comment]
Think I need to rebuild the container, let me try

**Comment by pditommaso** [comment]
Should be ok

**Comment by marcodelapierre** [comment]
yep

**Pull request merged**
