### PR TITLE
Fix `demo.nf`

### PR DESCRIPTION
**Pull request by melissachang**
Before this PR:

```
~/rnaseq-nf (master): nextflow run demo.nf
Launching `demo.nf` [maniac_williams] - revision: 352f3dbcea
WARN: DSL 2 PREVIEW MODE IS DEPRECATED - USE THE STABLE VERSION INSTEAD -- Read more at https://www.nextflow.io/docs/latest/dsl2.html#dsl2-migration-notes
Script compilation error
- file : /Users/melchang/rnaseq-nf/demo.nf
- cause: Workflow 'get' is not supported anymore use 'take' instead @ line 59, column 8.
     get: reads
          ^

Script compilation error
- file : /Users/melchang/rnaseq-nf/demo.nf
- cause: Workflow 'publish' is not supported anymore use process 'publishDir' instead @ line 59, column 8.
     get: reads
          ^

Script compilation error
- file : /Users/melchang/rnaseq-nf/demo.nf
- cause: Workflow 'get' is not supported anymore use 'take' instead @ line 64, column 7.
     get:reads
         ^

Script compilation error
- file : /Users/melchang/rnaseq-nf/demo.nf
- cause: Workflow 'publish' is not supported anymore use process 'publishDir' instead @ line 64, column 7.
     get:reads
         ^

4 errors
```

After this PR:

```
(salmon) ~/rnaseq-nf (mc/fix-demo): nextflow run demo.nf
N E X T F L O W  ~  version 21.10.6
Launching `demo.nf` [wise_newton] - revision: c39ccad44d
 R N A S E Q - N F   P I P E L I N E
 ===================================
 ref1:    : /Users/melchang/rnaseq-nf/data/ggal/ref1.fa
 ref2:    : /Users/melchang/rnaseq-nf/data/ggal/ref2.fa
 reads    : /Users/melchang/rnaseq-nf/data/ggal/ggal_gut_{1,2}.fq
 outdir   : results

executor >  local (6)
[c0/943f0e] process > ref1:RNASEQ:INDEX (ref1)       [100%] 1 of 1 ✔
[ed/160806] process > ref1:RNASEQ:FASTQC (FASTQC ... [100%] 1 of 1 ✔
[fc/33a70c] process > ref1:RNASEQ:QUANT (ggal_gut)   [100%] 1 of 1 ✔
[20/50df50] process > ref2:RNASEQ:INDEX (ref2)       [100%] 1 of 1 ✔
[09/34a2d2] process > ref2:RNASEQ:FASTQC (FASTQC ... [100%] 1 of 1 ✔
[c5/451565] process > ref2:RNASEQ:QUANT (ggal_gut)   [100%] 1 of 1 ✔

Done! Open the following report in your browser --> results/multiqc_report.html
```

### CODE REVIEW

**Comment by pditommaso** [comment]
Hello, thanks for submitting this. However, I think this script is not relevant anymore and should be deleted.

**Comment by melissachang** [comment]
We find it useful to have a demo workflow that runs quickly.

[We have a test that runs `main.nf` on `gls`.](https://github.com/DataBiosphere/terra-cli/blob/1e7ebd9522b2eb4fa90cf577dc61b21742468561/src/test/resources/testscripts/NextflowRnaseq.sh#L70)  The test takes around 10 minutes.

I'd like to switch the test to run `demo.nf`. Then, the test would take around 5 minutes. The overhead of running on `gls` is around 5 minutes.

It's useful to have `demo.nf` because it's very fast; when I run locally, it takes seconds. If I test against `demo.nf`, it makes sure everything is set up properly on GCP, without having to wait for actual rna-seq.

**Comment by pditommaso** [comment]
The `main.nf` should do the same

**Comment by pditommaso** [comment]
I read only now the difference of running time, but don't understand the reason. the demo is an only version of the main

**Comment by pditommaso** [comment]
Ok, looking at the code it seems that demo does not run multiqc, that should explain why is faster. 

However, I would suggest you use your own fork for running your tests. The file is not meant to be maintained in this repo

**Comment by melissachang** [comment]
Ok, thanks for taking a look

**Comment by melissachang** [comment]
@pditommaso  I'm looking for a simple demonstration nextflow workflow that finishes in seconds. This is for automated tests. Is there such a workflow in a different repo?

**Comment by pditommaso** [comment]
Yes https://github.com/nextflow-io/hello

**Pull request closed without merging**
