### PR TITLE
ChangeModulePATH_andrmConda

### PR DESCRIPTION
**Pull request by chriswyatt1**
OK, It was actually just everything that was done in the last PR that messed up the run. So you could revert back to https://github.com/nextflow-io/rnaseq-nf/commit/d5554945251185326451a60cc11bbc97953315dd

Can we just keep the conda part in the config?

### CODE REVIEW

**Comment by pditommaso** [comment]
I put there on purpose! what's the problem?

**Comment by chriswyatt1** [comment]
```
nextflow run https://github.com/nextflow-io/rnaseq-nf -with-docker

N E X T F L O W  ~  version 22.04.5
Pulling nextflow-io/rnaseq-nf ...
 downloaded from https://github.com/nextflow-io/rnaseq-nf.git
Launching `https://github.com/nextflow-io/rnaseq-nf` [magical_mestorf] DSL2 - revision: d555494525 [master]
 R N A S E Q - N F   P I P E L I N E
 ===================================
 transcriptome: /Users/cwyatt/.nextflow/assets/nextflow-io/rnaseq-nf/data/ggal/ggal_1_48850000_49020000.Ggal71.500bpflank.fa
 reads        : /Users/cwyatt/.nextflow/assets/nextflow-io/rnaseq-nf/data/ggal/ggal_gut_{1,2}.fq
 outdir       : results
 
Is a directory

 -- Check script '/Users/cwyatt/.nextflow/assets/nextflow-io/rnaseq-nf/./modules/rnaseq.nf' at line: 3 or see '.nextflow.log' file for more details
```

**Comment by chriswyatt1** [comment]
With the conda issue. On my local machine I have conda, but it still resulted in error when the tags on each module script was present,,, I find the error a sec

**Comment by chriswyatt1** [comment]
```
Oops .. something went wrong
executor >  local (1)
[-        ] process > RNASEQ:INDEX                       -
[2e/5a879d] process > RNASEQ:FASTQC (FASTQC on ggal_gut) [  0%] 0 of 1
[-        ] process > RNASEQ:QUANT                       -
[-        ] process > MULTIQC                            -
Creating env using conda: bioconda::salmon=1.6.0 [cache /Users/cwyatt/Downloads/rnaseq-nf/work/conda/env-1f2ce8f9b9b592a9d2acab23e823aac2]
Error executing process > 'RNASEQ:INDEX (ggal_1_48850000_49020000)'

Caused by:
  Failed to create Conda environment
  command: conda create --mkdir --yes --quiet --prefix /Users/cwyatt/Downloads/rnaseq-nf/work/conda/env-1f2ce8f9b9b592a9d2acab23e823aac2 bioconda::salmon=1.6.0
  status : 1
executor >  local (1)
[-        ] process > RNASEQ:INDEX                       -
[-        ] process > RNASEQ:FASTQC (FASTQC on ggal_gut) -
[-        ] process > RNASEQ:QUANT                       -
[-        ] process > MULTIQC                            -
Creating env using conda: bioconda::salmon=1.6.0 [cache /Users/cwyatt/Downloads/rnaseq-nf/work/conda/env-1f2ce8f9b9b592a9d2acab23e823aac2]
Error executing process > 'RNASEQ:INDEX (ggal_1_48850000_49020000)'

Caused by:
  Failed to create Conda environment
  command: conda create --mkdir --yes --quiet --prefix /Users/cwyatt/Downloads/rnaseq-nf/work/conda/env-1f2ce8f9b9b592a9d2acab23e823aac2 bioconda::salmon=1.6.0
  status : 1
  message:
    PackagesNotFoundError: The following packages are not available from current channels:
    
      - icu[version='>=68.2,<69.0a0']
    
    Current channels:
    
      - https://repo.anaconda.com/pkgs/main/osx-64
      - https://repo.anaconda.com/pkgs/main/noarch
      - https://repo.anaconda.com/pkgs/r/osx-64
      - https://repo.anaconda.com/pkgs/r/noarch
    
    To search for alternate channels that may provide the conda package you're
    looking for, navigate to
    
        https://anaconda.org
    
    and use the search bar at the top of the page.






```

**Comment by pditommaso** [comment]
Update your nextflow version, it's free!

**Comment by chriswyatt1** [comment]
Sorry, yes, was the version we were using on the training material! We should update the version from time to time and check all the expected code runs. Thanks

**Pull request closed without merging**
